import { PeriodicElement } from '../types/table-data';

export const ELEMENT_DATA: PeriodicElement[] = [
  {
    id: 1,
    name: 'Sofia Anicah',
    surname: 'Yutiga',
    hobby: 'Crying',
    age: 0,
    height: 0,
    weight: 0,
    language: 'English',
  },
  {
    id: 2,
    name: 'Sheila Marie',
    surname: 'Ero',
    hobby: 'Tiktok',
    age: 0,
    height: 0,
    weight: 0,
    language: 'English',
  },
  {
    id: 3,
    name: 'Arnel',
    surname: 'Yutiga',
    hobby: 'Coding',
    age: 0,
    height: 0,
    weight: 0,
    language: 'English',
  },
  {
    id: 4,
    name: 'Amelita',
    surname: 'Yutiga',
    hobby: 'Business',
    age: 0,
    height: 0,
    weight: 0,
    language: 'English',
  },
  {
    id: 5,
    name: 'Mary Joy',
    surname: 'Yutiga',
    hobby: 'School',
    age: 0,
    height: 0,
    weight: 0,
    language: 'English',
  },
  {
    id: 6,
    name: 'Michael',
    surname: 'Yutiga',
    hobby: 'Games',
    age: 0,
    height: 0,
    weight: 0,
    language: 'English',
  },
  {
    id: 7,
    name: 'Antonio',
    surname: 'Yutiga',
    hobby: 'Fixing Appliances',
    age: 0,
    height: 0,
    weight: 0,
    language: 'English',
  },
  {
    id: 8,
    name: 'Random',
    surname: 'Apilido',
    hobby: 'Any',
    age: 0,
    height: 0,
    weight: 0,
    language: 'English',
  },
  {
    id: 9,
    name: 'Nothing',
    surname: 'Word',
    hobby: 'Component',
    age: 0,
    height: 0,
    weight: 0,
    language: 'English',
  },
  {
    id: 10,
    name: 'Briliant',
    surname: 'Soccer',
    hobby: 'Tiktok',
    age: 0,
    height: 0,
    weight: 0,
    language: 'English',
  },
  {
    id: 11,
    name: 'Fixing',
    surname: 'Hero',
    hobby: 'Coding',
    age: 0,
    height: 0,
    weight: 0,
    language: 'English',
  },
  {
    id: 12,
    name: 'Page',
    surname: 'Table',
    hobby: 'Business',
    age: 0,
    height: 0,
    weight: 0,
    language: 'English',
  },
  {
    id: 13,
    name: 'ABC',
    surname: 'DEF',
    hobby: 'Crying',
    age: 0,
    height: 0,
    weight: 0,
    language: 'English',
  },
  {
    id: 14,
    name: 'Hello',
    surname: 'HI',
    hobby: 'Tiktok',
    age: 0,
    height: 0,
    weight: 0,
    language: 'English',
  },
  {
    id: 15,
    name: 'Outline',
    surname: 'Learn',
    hobby: 'Coding',
    age: 0,
    height: 0,
    weight: 0,
    language: 'English',
  },
  {
    id: 16,
    name: 'SRC',
    surname: 'Explorer',
    hobby: 'Business',
    age: 0,
    height: 0,
    weight: 0,
    language: 'English',
  },
  {
    id: 17,
    name: 'Angular',
    surname: 'Love',
    hobby: 'Crying',
    age: 0,
    height: 0,
    weight: 0,
    language: 'English',
  },
];
